### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by puja108** [giantswarm/example-opensource-repo#8]
GitHub now supports an `issue_template.md` file in the main directory of the repo, which is then automatically inserted when clicking "new issue".

For example see:
https://github.com/owncloud/core/issues/new
https://github.com/owncloud/core/blob/master/issue_template.md

**Comment by puja108** [comment]
ping @zeisss

**Comment by zeisss** [comment]
We noticed this from this: https://news.ycombinator.com/item?id=11116792

**Comment by marians** [comment]
Solved. See https://github.com/giantswarm/example-opensource-repo/blob/master/.github/ISSUE_TEMPLATE.md
